// Code generated by core_generate; DO NOT EDIT.

package leads

import (
	"net/http"

	"github.com/CrowdShield/go-core/lib/log"
	"github.com/CrowdShield/go-core/lib/router"
	"github.com/CrowdShield/go-core/lib/tools"
	"github.com/CrowdShield/go-core/lib/types"
	"github.com/go-chi/chi/v5"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/controllers/helpers"
	"github.com/griffnb/techboss-ai-go/internal/models/lead"
	"github.com/pkg/errors"
)

func adminIndex(_ http.ResponseWriter, req *http.Request) ([]*lead.LeadJoined, int, error) {

	parameters := router.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	leadObjs, err := lead.FindAllJoined(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.AdminBadRequestError[[]*lead.LeadJoined](err)

	}

	return helpers.Success(leadObjs)

}

func adminGet(_ http.ResponseWriter, req *http.Request) (*lead.LeadJoined, int, error) {
	id := chi.URLParam(req, "id")

	leadObj, err := lead.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.AdminBadRequestError[*lead.LeadJoined](err)
	}

	return helpers.Success(leadObj)
}

func adminCreate(_ http.ResponseWriter, req *http.Request) (*lead.Lead, int, error) {
	userSession := helpers.GetReqSession(req)
	rawdata := router.GetJSONPostData(req)
	data := helpers.ConvertPost(rawdata)
	leadObj := lead.New()
	leadObj.MergeData(data)
	err := leadObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.AdminBadRequestError[*lead.Lead](err)

	}

	return helpers.Success(leadObj)
}

func adminUpdate(_ http.ResponseWriter, req *http.Request) (*lead.LeadJoined, int, error) {
	userSession := helpers.GetReqSession(req)
	rawdata := router.GetJSONPostData(req)
	data := helpers.ConvertPost(rawdata)
	id := chi.URLParam(req, "id")
	leadObj, err := lead.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.AdminBadRequestError[*lead.LeadJoined](err)
	}

	if tools.Empty(leadObj) {
		return helpers.AdminBadRequestError[*lead.LeadJoined](errors.Errorf("Object not found with ID: %s", id))
	}

	leadObj.MergeData(data)
	err = leadObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.AdminBadRequestError[*lead.LeadJoined](err)
	}

	return helpers.Success(leadObj)
}

func adminCount(_ http.ResponseWriter, req *http.Request) (int64, int, error) {
	parameters := router.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)
	lead.AddJoinData(parameters)
	count, err := lead.FindResultsCount(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.AdminBadRequestError[int64](err)
	}

	return helpers.Success(count)
}
