// Code generated by core_generate; DO NOT EDIT.

package leads

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/griffnb/core/lib/log"
	"github.com/griffnb/core/lib/router/request"
	"github.com/griffnb/core/lib/router/response"
	"github.com/griffnb/core/lib/types"
	"github.com/griffnb/techboss-ai-go/internal/models/lead"
)

func authGet(_ http.ResponseWriter, req *http.Request) (*lead.LeadJoined, int, error) {

	user := request.GetReqSession(req).User

	id := chi.URLParam(req, "id")
	leadObj, err := lead.GetRestrictedJoined(req.Context(), types.UUID(id), user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*lead.LeadJoined]()

	}

	return response.Success(leadObj)
}

func authCreate(_ http.ResponseWriter, req *http.Request) (*lead.Lead, int, error) {

	user := request.GetReqSession(req).User

	data := request.GetModelPostData(req)
	leadObj := lead.NewPublic(data, user)
	err := leadObj.Save(user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*lead.Lead]()

	}

	return response.Success(leadObj)
}

func authUpdate(_ http.ResponseWriter, req *http.Request) (*lead.LeadJoined, int, error) {

	user := request.GetReqSession(req).User

	id := chi.URLParam(req, "id")
	data := request.GetModelPostData(req)
	leadObj, err := lead.GetRestrictedJoined(req.Context(), types.UUID(id), user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*lead.LeadJoined]()
	}

	lead.UpdatePublic(&leadObj.Lead, data, user)
	err = leadObj.Save(user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*lead.LeadJoined]()
	}

	return response.Success(leadObj)
}
