// Code generated by core_generate; DO NOT EDIT.

package account

import (
	"context"
	"sync"

	"github.com/CrowdShield/go-core/lib/log"
	"github.com/CrowdShield/go-core/lib/model"
	"github.com/CrowdShield/go-core/lib/model/coremodel"
	"github.com/CrowdShield/go-core/lib/model/fields"
	"github.com/CrowdShield/go-core/lib/tools"
)

var registerOnce sync.Once
var Columns *Account

const (
	PACKAGE string = "account"
	MODEL   string = "Account"
)

func init() {
	RegisterFields()
	Columns = New()
}

func RegisterFields() {
	registerOnce.Do(func() {
		fields.RegisterFieldTypes(&Structure{})
	})
}

func New() *Account {
	return NewType[*Account]()
}

func NewType[T initializable]() T {
	obj := tools.NewObj[T]()
	obj.InitializeWithChangeLogs(&model.InitializeOptions{
		Table:       TABLE,
		Model:       MODEL,
		ChangeLogs:  CHANGE_LOGS,
		Package:     PACKAGE,
		IsVersioned: IS_VERSIONED,
	})
	err := fields.InitializeFields(obj)
	if err != nil {
		log.Error(err)
	}
	return obj
}

type initializable interface {
	coremodel.Model
	InitializeWithChangeLogs(*model.InitializeOptions)
	Load(result map[string]any)
}

func load[T initializable](result map[string]any) T {
	obj := NewType[T]()
	obj.Load(result)
	return obj
}

func (this *Account) Save(savingUser coremodel.Model) error {
	return this.SaveWithContext(context.Background(), savingUser)
}

func (this *Account) SaveWithContext(ctx context.Context, savingUser coremodel.Model) error {
	err := this.beforeSave(ctx)
	if err != nil {
		return err
	}
	_, err = this.BaseSave(ctx, savingUser)
	if err != nil {
		return err
	}
	this.afterSave(ctx)
	return nil
}

func ConvertTo[T initializable, V initializable](souce T) V {
	target := NewType[V]()
	target.SetData(souce.GetDataCopy())
	return target
}
