// Code generated by core_gen; DO NOT EDIT.

package account

import (
	"time"

	"github.com/griffnb/techboss-ai-go/internal/models/billing_plan"
	"github.com/shopspring/decimal"
)

type GEN_Account struct {
	ID_                 string           `json:"id"`
	URN                 string           `json:"urn"`
	CreatedByURN        string           `json:"created_by_urn"`
	UpdatedByURN        string           `json:"updated_by_urn"`
	Status              int64            `json:"status"`
	Deleted             int64            `json:"deleted"`
	Disabled            int64            `json:"disabled"`
	UpdatedAt           time.Time        `json:"updated_at"`
	CreatedAt           time.Time        `json:"created_at"`
	FirstName           string           `json:"first_name"`
	LastName            string           `json:"last_name"`
	Email               string           `json:"email"`
	Phone               string           `json:"phone"`
	ExternalID          string           `json:"external_id"`
	TestUserType        int64            `json:"test_user_type"`
	OrganizationID      string           `json:"organization_id"`
	Role                int64            `json:"role"`
	Properties          Properties       `json:"properties"`
	SignupProperties    SignupProperties `json:"signup_properties"`
	HashedPassword      string           `json:"hashed_password"`
	PasswordUpdatedAtTS int64            `json:"password_updated_at_ts"`
	EmailVerifiedAtTS   int64            `json:"email_verified_at_ts"`
	LastLoginTS         int64            `json:"last_login_ts"`
	IsSuperUserSession  int64            `json:"is_super_user_session"`
} //@name AdminAccount

type GEN_AccountPublic struct {
	ID_                string    `json:"id"`
	URN                string    `json:"urn"`
	CreatedByURN       string    `json:"created_by_urn"`
	UpdatedByURN       string    `json:"updated_by_urn"`
	Status             int64     `json:"status"`
	Deleted            int64     `json:"deleted"`
	Disabled           int64     `json:"disabled"`
	UpdatedAt          time.Time `json:"updated_at"`
	CreatedAt          time.Time `json:"created_at"`
	FirstName          string    `json:"first_name"`
	LastName           string    `json:"last_name"`
	Email              string    `json:"email"`
	Phone              string    `json:"phone"`
	ExternalID         string    `json:"external_id"`
	TestUserType       int64     `json:"test_user_type"`
	OrganizationID     string    `json:"organization_id"`
	Role               int64     `json:"role"`
	IsSuperUserSession int64     `json:"is_super_user_session"`
} //@name Account

type GEN_AccountWithFeatures struct {
	ID_                   string                           `json:"id"`
	URN                   string                           `json:"urn"`
	CreatedByURN          string                           `json:"created_by_urn"`
	UpdatedByURN          string                           `json:"updated_by_urn"`
	Status                int64                            `json:"status"`
	Deleted               int64                            `json:"deleted"`
	Disabled              int64                            `json:"disabled"`
	UpdatedAt             time.Time                        `json:"updated_at"`
	CreatedAt             time.Time                        `json:"created_at"`
	FirstName             string                           `json:"first_name"`
	LastName              string                           `json:"last_name"`
	Email                 string                           `json:"email"`
	Phone                 string                           `json:"phone"`
	ExternalID            string                           `json:"external_id"`
	TestUserType          int64                            `json:"test_user_type"`
	OrganizationID        string                           `json:"organization_id"`
	Role                  int64                            `json:"role"`
	Properties            Properties                       `json:"properties"`
	SignupProperties      SignupProperties                 `json:"signup_properties"`
	HashedPassword        string                           `json:"hashed_password"`
	PasswordUpdatedAtTS   int64                            `json:"password_updated_at_ts"`
	EmailVerifiedAtTS     int64                            `json:"email_verified_at_ts"`
	LastLoginTS           int64                            `json:"last_login_ts"`
	IsSuperUserSession    int64                            `json:"is_super_user_session"`
	BillingPlanLevel      int64                            `json:"billing_plan_level"`
	BillingPlanPrice      decimal.Decimal                  `json:"billing_plan_price"`
	BillingPlanID         string                           `json:"billing_plan_id"`
	BillingPlanName       string                           `json:"billing_plan_name"`
	BillingPlanFeatureSet billing_plan.FeatureSet          `json:"billing_plan_feature_set"`
	FeatureSetOverrides   billing_plan.MergeableFeatureSet `json:"feature_set_overrides"`
	FeatureSet            billing_plan.FeatureSet          `json:"feature_set"`
} //@name AdminAccountWithFeatures

type GEN_AccountWithFeaturesPublic struct {
	ID_                string           `json:"id"`
	URN                string           `json:"urn"`
	CreatedByURN       string           `json:"created_by_urn"`
	UpdatedByURN       string           `json:"updated_by_urn"`
	Status             int64            `json:"status"`
	Deleted            int64            `json:"deleted"`
	Disabled           int64            `json:"disabled"`
	UpdatedAt          time.Time        `json:"updated_at"`
	CreatedAt          time.Time        `json:"created_at"`
	FirstName          string           `json:"first_name"`
	LastName           string           `json:"last_name"`
	Email              string           `json:"email"`
	Phone              string           `json:"phone"`
	ExternalID         string           `json:"external_id"`
	TestUserType       int64            `json:"test_user_type"`
	OrganizationID     string           `json:"organization_id"`
	Role               int64            `json:"role"`
	IsSuperUserSession int64            `json:"is_super_user_session"`
	BillingPlanLevel   int64            `json:"billing_plan_level"`
	BillingPlanPrice   decimal.Decimal  `json:"billing_plan_price"`
	BillingPlanID      string           `json:"billing_plan_id"`
	BillingPlanName    string           `json:"billing_plan_name"`
	FeatureSet         FeatureSetPublic `json:"feature_set"`
} //@name AccountWithFeatures

type GEN_AccountJoined struct {
	ID_                 string           `json:"id"`
	URN                 string           `json:"urn"`
	CreatedByURN        string           `json:"created_by_urn"`
	UpdatedByURN        string           `json:"updated_by_urn"`
	Status              int64            `json:"status"`
	Deleted             int64            `json:"deleted"`
	Disabled            int64            `json:"disabled"`
	UpdatedAt           time.Time        `json:"updated_at"`
	CreatedAt           time.Time        `json:"created_at"`
	FirstName           string           `json:"first_name"`
	LastName            string           `json:"last_name"`
	Email               string           `json:"email"`
	Phone               string           `json:"phone"`
	ExternalID          string           `json:"external_id"`
	TestUserType        int64            `json:"test_user_type"`
	OrganizationID      string           `json:"organization_id"`
	Role                int64            `json:"role"`
	Properties          Properties       `json:"properties"`
	SignupProperties    SignupProperties `json:"signup_properties"`
	HashedPassword      string           `json:"hashed_password"`
	PasswordUpdatedAtTS int64            `json:"password_updated_at_ts"`
	EmailVerifiedAtTS   int64            `json:"email_verified_at_ts"`
	LastLoginTS         int64            `json:"last_login_ts"`
	IsSuperUserSession  int64            `json:"is_super_user_session"`
	Name                string           `json:"name"`
	OrganizationName    string           `json:"organization_name"`
	CreatedByName       string           `json:"created_by_name"`
	UpdatedByName       string           `json:"updated_by_name"`
} //@name AdminAccountJoined

type GEN_AccountJoinedPublic struct {
	ID_                string    `json:"id"`
	URN                string    `json:"urn"`
	CreatedByURN       string    `json:"created_by_urn"`
	UpdatedByURN       string    `json:"updated_by_urn"`
	Status             int64     `json:"status"`
	Deleted            int64     `json:"deleted"`
	Disabled           int64     `json:"disabled"`
	UpdatedAt          time.Time `json:"updated_at"`
	CreatedAt          time.Time `json:"created_at"`
	FirstName          string    `json:"first_name"`
	LastName           string    `json:"last_name"`
	Email              string    `json:"email"`
	Phone              string    `json:"phone"`
	ExternalID         string    `json:"external_id"`
	TestUserType       int64     `json:"test_user_type"`
	OrganizationID     string    `json:"organization_id"`
	Role               int64     `json:"role"`
	IsSuperUserSession int64     `json:"is_super_user_session"`
}

type FeatureSetPublic struct {
}
