// Code generated by core_generate; DO NOT EDIT.

package account

import (
	"database/sql/driver"
	"encoding/json"

	aws_types "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	"github.com/griffnb/core/lib/model"
	"github.com/griffnb/core/lib/model/fields"
	"github.com/pkg/errors"
)

// UnmarshalJSON interface
func (this *Account) UnmarshalJSON(data []byte) error {
	this.InitializeWithChangeLogs(&model.InitializeOptions{
		Table:       TABLE,
		Model:       MODEL,
		ChangeLogs:  CHANGE_LOGS,
		Package:     PACKAGE,
		IsVersioned: IS_VERSIONED,
	})
	err := fields.InitializeFields(this)
	if err != nil {
		return err
	}

	return this.BaseModel.UnmarshalJSON(data)
}

// UnmarshalDynamoDBAttributeValue interface
func (this *Account) UnmarshalDynamoDBAttributeValue(av aws_types.AttributeValue) error {
	this.InitializeWithChangeLogs(&model.InitializeOptions{
		Table:       TABLE,
		Model:       MODEL,
		ChangeLogs:  CHANGE_LOGS,
		Package:     PACKAGE,
		IsVersioned: IS_VERSIONED,
	})
	err := fields.InitializeFields(this)
	if err != nil {
		return err
	}

	return this.BaseModel.UnmarshalDynamoDBAttributeValue(av)
}

func (r *Account) Scan(src any) error {
	switch v := src.(type) {
	case nil:
		*r = Account{}
		return nil
	case []byte:
		return errors.WithStack(json.Unmarshal(v, r))
	case string:
		return errors.WithStack(json.Unmarshal([]byte(v), r))
	default:
		return errors.Errorf("Account.Scan: unsupported type %T", src)
	}
}

func (r *Account) Value() (driver.Value, error) {
	b, err := json.Marshal(r)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	return string(b), nil // or b
}
