// Code generated by core_gen; DO NOT EDIT.

package modal

import (
	context "context"
	http "net/http"

	types "github.com/griffnb/core/lib/types"
)

// APIClientInterface defines the methods implemented by APIClient and MockAPIClient.
type APIClientInterface interface {
	CreateSandbox(ctx context.Context, config *SandboxConfig) (*SandboxInfo, error)
	ExecClaude(ctx context.Context, sandboxInfo *SandboxInfo, config *ClaudeExecConfig) (*ClaudeProcess, error)
	GetLatestVersion(ctx context.Context, accountID types.UUID, bucketName string) (int64, error)
	GetSandboxStatus(_ context.Context, sandboxID string) (SandboxStatus, error)
	GetSandboxStatusFromInfo(ctx context.Context, sandboxInfo *SandboxInfo) (SandboxStatus, error)
	InitVolumeFromS3(ctx context.Context, sandboxInfo *SandboxInfo) (*SyncStats, error)
	StreamClaudeOutput(ctx context.Context, claudeProcess *ClaudeProcess, responseWriter http.ResponseWriter) error
	SyncVolumeToS3(ctx context.Context, sandboxInfo *SandboxInfo) (*SyncStats, error)
	TerminateSandbox(ctx context.Context, sandboxInfo *SandboxInfo, syncToS3 bool) error
	WaitForClaude(ctx context.Context, claudeProcess *ClaudeProcess) (int, error)
}

type MockAPIClient struct {
	*APIClient
	CreateSandboxFunc            func(ctx context.Context, config *SandboxConfig) (*SandboxInfo, error)
	ExecClaudeFunc               func(ctx context.Context, sandboxInfo *SandboxInfo, config *ClaudeExecConfig) (*ClaudeProcess, error)
	GetLatestVersionFunc         func(ctx context.Context, accountID types.UUID, bucketName string) (int64, error)
	GetSandboxStatusFunc         func(_ context.Context, sandboxID string) (SandboxStatus, error)
	GetSandboxStatusFromInfoFunc func(ctx context.Context, sandboxInfo *SandboxInfo) (SandboxStatus, error)
	InitVolumeFromS3Func         func(ctx context.Context, sandboxInfo *SandboxInfo) (*SyncStats, error)
	StreamClaudeOutputFunc       func(ctx context.Context, claudeProcess *ClaudeProcess, responseWriter http.ResponseWriter) error
	SyncVolumeToS3Func           func(ctx context.Context, sandboxInfo *SandboxInfo) (*SyncStats, error)
	TerminateSandboxFunc         func(ctx context.Context, sandboxInfo *SandboxInfo, syncToS3 bool) error
	WaitForClaudeFunc            func(ctx context.Context, claudeProcess *ClaudeProcess) (int, error)
}

// CreateSandbox overrides the real implementation for MockAPIClient.
func (m *MockAPIClient) CreateSandbox(ctx context.Context, config *SandboxConfig) (*SandboxInfo, error) {
	if m.CreateSandboxFunc != nil {
		return m.CreateSandboxFunc(ctx, config)
	}
	if m.APIClient == nil {
		return nil, nil
	}
	return m.APIClient.CreateSandbox(ctx, config)
}

// ExecClaude overrides the real implementation for MockAPIClient.
func (m *MockAPIClient) ExecClaude(ctx context.Context, sandboxInfo *SandboxInfo, config *ClaudeExecConfig) (*ClaudeProcess, error) {
	if m.ExecClaudeFunc != nil {
		return m.ExecClaudeFunc(ctx, sandboxInfo, config)
	}
	if m.APIClient == nil {
		return nil, nil
	}
	return m.APIClient.ExecClaude(ctx, sandboxInfo, config)
}

// GetLatestVersion overrides the real implementation for MockAPIClient.
func (m *MockAPIClient) GetLatestVersion(ctx context.Context, accountID types.UUID, bucketName string) (int64, error) {
	if m.GetLatestVersionFunc != nil {
		return m.GetLatestVersionFunc(ctx, accountID, bucketName)
	}
	if m.APIClient == nil {
		return 0, nil
	}
	return m.APIClient.GetLatestVersion(ctx, accountID, bucketName)
}

// GetSandboxStatus overrides the real implementation for MockAPIClient.
func (m *MockAPIClient) GetSandboxStatus(ctx context.Context, sandboxID string) (SandboxStatus, error) {
	if m.GetSandboxStatusFunc != nil {
		return m.GetSandboxStatusFunc(ctx, sandboxID)
	}
	if m.APIClient == nil {
		return "", nil
	}
	return m.APIClient.GetSandboxStatus(ctx, sandboxID)
}

// GetSandboxStatusFromInfo overrides the real implementation for MockAPIClient.
func (m *MockAPIClient) GetSandboxStatusFromInfo(ctx context.Context, sandboxInfo *SandboxInfo) (SandboxStatus, error) {
	if m.GetSandboxStatusFromInfoFunc != nil {
		return m.GetSandboxStatusFromInfoFunc(ctx, sandboxInfo)
	}
	if m.APIClient == nil {
		return "", nil
	}
	return m.APIClient.GetSandboxStatusFromInfo(ctx, sandboxInfo)
}

// InitVolumeFromS3 overrides the real implementation for MockAPIClient.
func (m *MockAPIClient) InitVolumeFromS3(ctx context.Context, sandboxInfo *SandboxInfo) (*SyncStats, error) {
	if m.InitVolumeFromS3Func != nil {
		return m.InitVolumeFromS3Func(ctx, sandboxInfo)
	}
	if m.APIClient == nil {
		return nil, nil
	}
	return m.APIClient.InitVolumeFromS3(ctx, sandboxInfo)
}

// StreamClaudeOutput overrides the real implementation for MockAPIClient.
func (m *MockAPIClient) StreamClaudeOutput(ctx context.Context, claudeProcess *ClaudeProcess, responseWriter http.ResponseWriter) error {
	if m.StreamClaudeOutputFunc != nil {
		return m.StreamClaudeOutputFunc(ctx, claudeProcess, responseWriter)
	}
	if m.APIClient == nil {
		return nil
	}
	return m.APIClient.StreamClaudeOutput(ctx, claudeProcess, responseWriter)
}

// SyncVolumeToS3 overrides the real implementation for MockAPIClient.
func (m *MockAPIClient) SyncVolumeToS3(ctx context.Context, sandboxInfo *SandboxInfo) (*SyncStats, error) {
	if m.SyncVolumeToS3Func != nil {
		return m.SyncVolumeToS3Func(ctx, sandboxInfo)
	}
	if m.APIClient == nil {
		return nil, nil
	}
	return m.APIClient.SyncVolumeToS3(ctx, sandboxInfo)
}

// TerminateSandbox overrides the real implementation for MockAPIClient.
func (m *MockAPIClient) TerminateSandbox(ctx context.Context, sandboxInfo *SandboxInfo, syncToS3 bool) error {
	if m.TerminateSandboxFunc != nil {
		return m.TerminateSandboxFunc(ctx, sandboxInfo, syncToS3)
	}
	if m.APIClient == nil {
		return nil
	}
	return m.APIClient.TerminateSandbox(ctx, sandboxInfo, syncToS3)
}

// WaitForClaude overrides the real implementation for MockAPIClient.
func (m *MockAPIClient) WaitForClaude(ctx context.Context, claudeProcess *ClaudeProcess) (int, error) {
	if m.WaitForClaudeFunc != nil {
		return m.WaitForClaudeFunc(ctx, claudeProcess)
	}
	if m.APIClient == nil {
		return 0, nil
	}
	return m.APIClient.WaitForClaude(ctx, claudeProcess)
}
