// Code generated by core_gen; DO NOT EDIT.

package lifecycle_test_placeholder

import (
	"context"

	"github.com/griffnb/core/lib/log"
	"github.com/griffnb/core/lib/model"
	"github.com/griffnb/core/lib/types"
	"github.com/griffnb/techboss-ai-go/internal/environment"
)

func FindAll(ctx context.Context, options *model.Options) ([]*LifecycleTestPlaceholder, error) {
	mocker, ok := model.GetMocker[*Mocker](ctx, PACKAGE)
	if ok {
		return mocker.FindAll(ctx, options)
	}
	return all[*LifecycleTestPlaceholder](ctx, options)
}

func FindFirst(ctx context.Context, options *model.Options) (*LifecycleTestPlaceholder, error) {
	mocker, ok := model.GetMocker[*Mocker](ctx, PACKAGE)
	if ok {
		return mocker.FindFirst(ctx, options)
	}
	return first[*LifecycleTestPlaceholder](ctx, options)
}

func Get(ctx context.Context, id types.UUID) (*LifecycleTestPlaceholder, error) {
	mocker, ok := model.GetMocker[*Mocker](ctx, PACKAGE)
	if ok {
		return mocker.Get(ctx, id)
	}
	return get[*LifecycleTestPlaceholder](ctx, id)
}

func FindResultsCount(ctx context.Context, options *model.Options) (int64, error) {
	mocker, ok := model.GetMocker[*Mocker](ctx, PACKAGE)
	if ok {
		return mocker.FindResultsCount(ctx, options)
	}
	return environment.GetDBClient(CLIENT).FindResultsCount(ctx, TABLE, options)
}

// GetJoined gets a record with a specific ID and joins the hierarchy to it
func GetJoined(ctx context.Context, id types.UUID) (*LifecycleTestPlaceholderJoined, error) {
	mocker, ok := model.GetMocker[*Mocker](ctx, PACKAGE)
	if ok {
		return mocker.GetJoined(ctx, id)
	}
	options := model.NewOptions().
		WithCondition("%s = :id:", Columns.ID_.Column()).
		WithParam(":id:", id)

	AddJoinData(options)
	return first[*LifecycleTestPlaceholderJoined](ctx, options)
}

// FindFirstJoined Finds first record
func FindFirstJoined(ctx context.Context, options *model.Options) (*LifecycleTestPlaceholderJoined, error) {
	mocker, ok := model.GetMocker[*Mocker](ctx, PACKAGE)
	if ok {
		return mocker.FindFirstJoined(ctx, options)
	}
	AddJoinData(options)
	return first[*LifecycleTestPlaceholderJoined](ctx, options)
}

// FindAllJoined Finds all records
func FindAllJoined(ctx context.Context, options *model.Options) ([]*LifecycleTestPlaceholderJoined, error) {
	mocker, ok := model.GetMocker[*Mocker](ctx, PACKAGE)
	if ok {
		return mocker.FindAllJoined(ctx, options)
	}
	AddJoinData(options)
	return all[*LifecycleTestPlaceholderJoined](ctx, options)
}

func all[T initializable](ctx context.Context, options *model.Options) ([]T, error) {
	results, err := environment.GetDBClient(CLIENT).FindAll(ctx, TABLE, options)
	if err != nil {
		return nil, err
	}

	modelResults := make([]T, len(results))
	for i, result := range results {
		obj := load[T](result)
		modelResults[i] = obj
	}
	return modelResults, nil
}

func first[T initializable](ctx context.Context, options *model.Options) (T, error) {
	result, err := environment.GetDBClient(CLIENT).FindFirst(ctx, TABLE, options)
	if err != nil {
		return *new(T), err
	}

	return load[T](result), nil
}

func get[T initializable](ctx context.Context, id types.UUID) (T, error) {
	result, err := environment.GetDBClient(CLIENT).Find(ctx, TABLE, id)
	if err != nil {
		log.Error(err)
		return *new(T), err
	}

	return load[T](result), nil
}
