package main

import (
	"log"
	"net/http"

	"github.com/go-chi/chi/v5"
	_ "github.com/griffnb/techboss-ai-go/swag_docs" // docs is generated by Swag CLI, you have to import it.
	httpSwagger "github.com/swaggo/http-swagger"
)

func main() {
	r := chi.NewRouter()

	// CORS middleware with wildcard
	r.Use(Cors)

	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:1323/swagger/doc.json"), // The url pointing to API definition
	))

	// Serve static swagger files
	r.Get("/swag_docs/swagger.json", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "./swag_docs/swagger.json")
	})
	r.Get("/swag_docs/swagger.yaml", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "./swag_docs/swagger.yaml")
	})

	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "./swag_docs/swagger.yaml")
	})

	log.Fatal(http.ListenAndServe(":1323", r))
}

func Cors(next http.Handler) http.Handler {
	return http.HandlerFunc(func(res http.ResponseWriter, req *http.Request) {
		origin := req.Header.Get("Origin")

		res.Header().Set("Access-Control-Allow-Origin", origin)

		res.Header().Set("Access-Control-Allow-Methods", "GET,POST,PUT,DELETE,OPTIONS")
		res.Header().Set("Access-Control-Allow-Credentials", "true")
		res.Header().Set("Access-Control-Allow-Headers", req.Header.Get("Access-Control-Request-Headers"))

		if req.Method != "OPTIONS" {
			next.ServeHTTP(res, req)
		}
	})
}
