// Code generated by core_generate; DO NOT EDIT.

package admin

import (
	"github.com/CrowdShield/go-core/lib/model"
	"github.com/CrowdShield/go-core/lib/model/fields"
	aws_types "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
)

// UnmarshalJSON interface
func (this *Admin) UnmarshalJSON(data []byte) error {
	this.InitializeWithChangeLogs(&model.InitializeOptions{
		Table:       TABLE,
		Model:       MODEL,
		ChangeLogs:  CHANGE_LOGS,
		Package:     PACKAGE,
		IsVersioned: IS_VERSIONED,
	})
	err := fields.InitializeFields(this)
	if err != nil {
		return err
	}

	return this.BaseModel.UnmarshalJSON(data)
}

// UnmarshalDynamoDBAttributeValue interface
func (this *Admin) UnmarshalDynamoDBAttributeValue(av aws_types.AttributeValue) error {
	this.InitializeWithChangeLogs(&model.InitializeOptions{
		Table:       TABLE,
		Model:       MODEL,
		ChangeLogs:  CHANGE_LOGS,
		Package:     PACKAGE,
		IsVersioned: IS_VERSIONED,
	})
	err := fields.InitializeFields(this)
	if err != nil {
		return err
	}

	return this.BaseModel.UnmarshalDynamoDBAttributeValue(av)
}
