// Code generated by core_gen; DO NOT EDIT.

package sandboxes

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/griffnb/core/lib/log"
	"github.com/griffnb/core/lib/router/request"
	"github.com/griffnb/core/lib/router/response"
	"github.com/griffnb/core/lib/tools"
	"github.com/griffnb/core/lib/types"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/models/sandbox"
	"github.com/pkg/errors"
)

func adminIndex(_ http.ResponseWriter, req *http.Request) ([]*sandbox.SandboxJoined, int, error) {

	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	sandboxObjs, err := sandbox.FindAllJoined(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[[]*sandbox.SandboxJoined](err)

	}

	return response.Success(sandboxObjs)

}

func adminGet(_ http.ResponseWriter, req *http.Request) (*sandbox.SandboxJoined, int, error) {
	id := chi.URLParam(req, "id")

	sandboxObj, err := sandbox.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*sandbox.SandboxJoined](err)
	}

	return response.Success(sandboxObj)
}

func adminCreate(_ http.ResponseWriter, req *http.Request) (*sandbox.Sandbox, int, error) {
	userSession := request.GetReqSession(req)
	data := request.GetModelPostData(req)
	sandboxObj := sandbox.New()
	sandboxObj.MergeData(data)
	err := sandboxObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*sandbox.Sandbox](err)

	}

	return response.Success(sandboxObj)
}

func adminUpdate(_ http.ResponseWriter, req *http.Request) (*sandbox.SandboxJoined, int, error) {
	userSession := request.GetReqSession(req)
	data := request.GetModelPostData(req)
	id := chi.URLParam(req, "id")
	sandboxObj, err := sandbox.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*sandbox.SandboxJoined](err)
	}

	if tools.Empty(sandboxObj) {
		return response.AdminBadRequestError[*sandbox.SandboxJoined](errors.Errorf("Object not found with ID: %s", id))
	}

	sandboxObj.MergeData(data)
	err = sandboxObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*sandbox.SandboxJoined](err)
	}

	return response.Success(sandboxObj)
}

func adminCount(_ http.ResponseWriter, req *http.Request) (int64, int, error) {
	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)
	sandbox.AddJoinData(parameters)
	count, err := sandbox.FindResultsCount(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[int64](err)
	}

	return response.Success(count)
}
