// Code generated by core_gen; DO NOT EDIT.

package sandboxes

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/griffnb/core/lib/log"
	"github.com/griffnb/core/lib/router/request"
	"github.com/griffnb/core/lib/router/response"
	"github.com/griffnb/core/lib/tools"
	"github.com/griffnb/core/lib/types"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/models/sandbox"
)

func authIndex(_ http.ResponseWriter, req *http.Request) ([]*sandbox.SandboxJoined, int, error) {

	user := request.GetReqSession(req).User

	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	sandboxObjs, err := sandbox.FindAllRestrictedJoined(req.Context(), parameters, user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[[]*sandbox.SandboxJoined]()

	}

	return response.Success(sandboxObjs)
}

func authGet(_ http.ResponseWriter, req *http.Request) (*sandbox.SandboxJoined, int, error) {

	user := request.GetReqSession(req).User

	id := chi.URLParam(req, "id")
	sandboxObj, err := sandbox.GetRestrictedJoined(req.Context(), types.UUID(id), user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*sandbox.SandboxJoined]()

	}

	return response.Success(sandboxObj)
}
