// Code generated by core_generate; DO NOT EDIT.

package conversations

import (
	"net/http"

	"github.com/CrowdShield/go-core/lib/log"
	"github.com/CrowdShield/go-core/lib/router/request"
	"github.com/CrowdShield/go-core/lib/router/response"
	"github.com/CrowdShield/go-core/lib/tools"
	"github.com/CrowdShield/go-core/lib/types"
	"github.com/go-chi/chi/v5"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/models/conversation"
)

func authIndex(_ http.ResponseWriter, req *http.Request) ([]*conversation.ConversationJoined, int, error) {

	user := request.GetReqSession(req).User

	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	conversationObjs, err := conversation.FindAllRestrictedJoined(req.Context(), parameters, user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[[]*conversation.ConversationJoined]()

	}

	return response.Success(conversationObjs)
}

func authGet(_ http.ResponseWriter, req *http.Request) (*conversation.ConversationJoined, int, error) {

	user := request.GetReqSession(req).User

	id := chi.URLParam(req, "id")
	conversationObj, err := conversation.GetRestrictedJoined(req.Context(), types.UUID(id), user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*conversation.ConversationJoined]()

	}

	return response.Success(conversationObj)
}

func authCreate(_ http.ResponseWriter, req *http.Request) (*conversation.Conversation, int, error) {

	user := request.GetReqSession(req).User

	data := request.GetModelPostData(req)
	conversationObj := conversation.NewPublic(data, user)
	err := conversationObj.Save(user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*conversation.Conversation]()

	}

	return response.Success(conversationObj)
}

func authUpdate(_ http.ResponseWriter, req *http.Request) (*conversation.ConversationJoined, int, error) {

	user := request.GetReqSession(req).User

	id := chi.URLParam(req, "id")
	data := request.GetModelPostData(req)
	conversationObj, err := conversation.GetRestrictedJoined(req.Context(), types.UUID(id), user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*conversation.ConversationJoined]()
	}

	conversation.UpdatePublic(&conversationObj.Conversation, data, user)
	err = conversationObj.Save(user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*conversation.ConversationJoined]()
	}

	return response.Success(conversationObj)
}
