// Code generated by core_generate; DO NOT EDIT.

package documents

import (
	"net/http"

	"github.com/CrowdShield/go-core/lib/log"
	"github.com/CrowdShield/go-core/lib/router/request"
	"github.com/CrowdShield/go-core/lib/router/response"
	"github.com/CrowdShield/go-core/lib/tools"
	"github.com/CrowdShield/go-core/lib/types"
	"github.com/go-chi/chi/v5"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/models/document"
)

func authIndex(_ http.ResponseWriter, req *http.Request) ([]*document.DocumentJoined, int, error) {

	user := request.GetReqSession(req).User

	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	documentObjs, err := document.FindAllRestrictedJoined(req.Context(), parameters, user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[[]*document.DocumentJoined]()

	}

	return response.Success(documentObjs)
}

func authGet(_ http.ResponseWriter, req *http.Request) (*document.DocumentJoined, int, error) {

	user := request.GetReqSession(req).User

	id := chi.URLParam(req, "id")
	documentObj, err := document.GetRestrictedJoined(req.Context(), types.UUID(id), user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*document.DocumentJoined]()

	}

	return response.Success(documentObj)
}

func authCreate(_ http.ResponseWriter, req *http.Request) (*document.Document, int, error) {

	user := request.GetReqSession(req).User

	data := request.GetModelPostData(req)
	documentObj := document.NewPublic(data, user)
	err := documentObj.Save(user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*document.Document]()

	}

	return response.Success(documentObj)
}

func authUpdate(_ http.ResponseWriter, req *http.Request) (*document.DocumentJoined, int, error) {

	user := request.GetReqSession(req).User

	id := chi.URLParam(req, "id")
	data := request.GetModelPostData(req)
	documentObj, err := document.GetRestrictedJoined(req.Context(), types.UUID(id), user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*document.DocumentJoined]()
	}

	document.UpdatePublic(&documentObj.Document, data, user)
	err = documentObj.Save(user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*document.DocumentJoined]()
	}

	return response.Success(documentObj)
}
