// Code generated by core_generate; DO NOT EDIT.

package categories

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/griffnb/core/lib/log"
	"github.com/griffnb/core/lib/router/request"
	"github.com/griffnb/core/lib/router/response"
	"github.com/griffnb/core/lib/tools"
	"github.com/griffnb/core/lib/types"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/models/category"
)

func authIndex(_ http.ResponseWriter, req *http.Request) ([]*category.CategoryJoined, int, error) {

	user := request.GetReqSession(req).User

	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	categoryObjs, err := category.FindAllRestrictedJoined(req.Context(), parameters, user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[[]*category.CategoryJoined]()

	}

	return response.Success(categoryObjs)
}

func authGet(_ http.ResponseWriter, req *http.Request) (*category.CategoryJoined, int, error) {

	user := request.GetReqSession(req).User

	id := chi.URLParam(req, "id")
	categoryObj, err := category.GetRestrictedJoined(req.Context(), types.UUID(id), user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*category.CategoryJoined]()

	}

	return response.Success(categoryObj)
}

func authCreate(_ http.ResponseWriter, req *http.Request) (*category.Category, int, error) {

	user := request.GetReqSession(req).User

	data := request.GetModelPostData(req)
	categoryObj := category.NewPublic(data, user)
	err := categoryObj.Save(user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*category.Category]()

	}

	return response.Success(categoryObj)
}

func authUpdate(_ http.ResponseWriter, req *http.Request) (*category.CategoryJoined, int, error) {

	user := request.GetReqSession(req).User

	id := chi.URLParam(req, "id")
	data := request.GetModelPostData(req)
	categoryObj, err := category.GetRestrictedJoined(req.Context(), types.UUID(id), user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*category.CategoryJoined]()
	}

	category.UpdatePublic(&categoryObj.Category, data, user)
	err = categoryObj.Save(user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*category.CategoryJoined]()
	}

	return response.Success(categoryObj)
}
