// Code generated by core_generate; DO NOT EDIT.

package admins

import (
	"net/http"

	"github.com/CrowdShield/go-core/lib/log"
	"github.com/CrowdShield/go-core/lib/router"
	"github.com/CrowdShield/go-core/lib/tools"
	"github.com/CrowdShield/go-core/lib/types"
	"github.com/go-chi/chi/v5"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/controllers/helpers"
	"github.com/griffnb/techboss-ai-go/internal/models/admin"
	"github.com/pkg/errors"
)

func adminIndex(_ http.ResponseWriter, req *http.Request) ([]*admin.AdminJoined, int, error) {

	parameters := router.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	adminObjs, err := admin.FindAllJoined(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.AdminBadRequestError[[]*admin.AdminJoined](err)

	}

	return helpers.Success(adminObjs)

}

func adminGet(_ http.ResponseWriter, req *http.Request) (*admin.AdminJoined, int, error) {
	id := chi.URLParam(req, "id")

	adminObj, err := admin.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.AdminBadRequestError[*admin.AdminJoined](err)
	}

	return helpers.Success(adminObj)
}

func adminCreate(_ http.ResponseWriter, req *http.Request) (*admin.Admin, int, error) {
	userSession := helpers.GetReqSession(req)
	rawdata := router.GetJSONPostData(req)
	data := helpers.ConvertPost(rawdata)
	adminObj := admin.New()
	adminObj.MergeData(data)
	err := adminObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.AdminBadRequestError[*admin.Admin](err)

	}

	return helpers.Success(adminObj)
}

func adminUpdate(_ http.ResponseWriter, req *http.Request) (*admin.AdminJoined, int, error) {
	userSession := helpers.GetReqSession(req)
	rawdata := router.GetJSONPostData(req)
	data := helpers.ConvertPost(rawdata)
	id := chi.URLParam(req, "id")
	adminObj, err := admin.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.AdminBadRequestError[*admin.AdminJoined](err)
	}

	if tools.Empty(adminObj) {
		return helpers.AdminBadRequestError[*admin.AdminJoined](errors.Errorf("Object not found with ID: %s", id))
	}

	adminObj.MergeData(data)
	err = adminObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.AdminBadRequestError[*admin.AdminJoined](err)
	}

	return helpers.Success(adminObj)
}

func adminCount(_ http.ResponseWriter, req *http.Request) (int64, int, error) {
	parameters := router.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)
	admin.AddJoinData(parameters)
	count, err := admin.FindResultsCount(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.AdminBadRequestError[int64](err)
	}

	return helpers.Success(count)
}
