// Code generated by core_gen; DO NOT EDIT.

package billing_plan_prices

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/griffnb/core/lib/log"
	"github.com/griffnb/core/lib/router/request"
	"github.com/griffnb/core/lib/router/response"
	"github.com/griffnb/core/lib/tools"
	"github.com/griffnb/core/lib/types"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/models/billing_plan_price"
)

func adminIndex(_ http.ResponseWriter, req *http.Request) ([]*billing_plan_price.BillingPlanPriceJoined, int, error) {

	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	billingPlanPriceObjs, err := billing_plan_price.FindAllJoined(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[[]*billing_plan_price.BillingPlanPriceJoined](err)

	}

	return response.Success(billingPlanPriceObjs)

}

func adminGet(_ http.ResponseWriter, req *http.Request) (*billing_plan_price.BillingPlanPriceJoined, int, error) {
	id := chi.URLParam(req, "id")

	billingPlanPriceObj, err := billing_plan_price.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*billing_plan_price.BillingPlanPriceJoined](err)
	}

	return response.Success(billingPlanPriceObj)
}

func adminCount(_ http.ResponseWriter, req *http.Request) (int64, int, error) {
	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)
	billing_plan_price.AddJoinData(parameters)
	count, err := billing_plan_price.FindResultsCount(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[int64](err)
	}

	return response.Success(count)
}
