// Code generated by core_gen; DO NOT EDIT.

package billing_plan_prices

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/griffnb/core/lib/log"
	"github.com/griffnb/core/lib/router/request"
	"github.com/griffnb/core/lib/router/response"
	"github.com/griffnb/core/lib/tools"
	"github.com/griffnb/core/lib/types"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/models/billing_plan_price"
)

func authIndex(_ http.ResponseWriter, req *http.Request) ([]*billing_plan_price.BillingPlanPriceJoined, int, error) {

	user := request.GetReqSession(req).User

	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	billingPlanPriceObjs, err := billing_plan_price.FindAllRestrictedJoined(req.Context(), parameters, user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[[]*billing_plan_price.BillingPlanPriceJoined]()

	}

	return response.Success(billingPlanPriceObjs)
}

func authGet(_ http.ResponseWriter, req *http.Request) (*billing_plan_price.BillingPlanPriceJoined, int, error) {

	user := request.GetReqSession(req).User

	id := chi.URLParam(req, "id")
	billingPlanPriceObj, err := billing_plan_price.GetRestrictedJoined(req.Context(), types.UUID(id), user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*billing_plan_price.BillingPlanPriceJoined]()

	}

	return response.Success(billingPlanPriceObj)
}
