// Code generated by core_gen; DO NOT EDIT.

package subscriptions

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/griffnb/core/lib/log"
	"github.com/griffnb/core/lib/router/request"
	"github.com/griffnb/core/lib/router/response"
	"github.com/griffnb/core/lib/tools"
	"github.com/griffnb/core/lib/types"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/models/subscription"
	"github.com/pkg/errors"
)

func adminIndex(_ http.ResponseWriter, req *http.Request) ([]*subscription.SubscriptionJoined, int, error) {

	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	subscriptionObjs, err := subscription.FindAllJoined(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[[]*subscription.SubscriptionJoined](err)

	}

	return response.Success(subscriptionObjs)

}

func adminGet(_ http.ResponseWriter, req *http.Request) (*subscription.SubscriptionJoined, int, error) {
	id := chi.URLParam(req, "id")

	subscriptionObj, err := subscription.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*subscription.SubscriptionJoined](err)
	}

	return response.Success(subscriptionObj)
}

func adminCreate(_ http.ResponseWriter, req *http.Request) (*subscription.Subscription, int, error) {
	userSession := request.GetReqSession(req)
	data := request.GetModelPostData(req)
	subscriptionObj := subscription.New()
	subscriptionObj.MergeData(data)
	err := subscriptionObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*subscription.Subscription](err)

	}

	return response.Success(subscriptionObj)
}

func adminUpdate(_ http.ResponseWriter, req *http.Request) (*subscription.SubscriptionJoined, int, error) {
	userSession := request.GetReqSession(req)
	data := request.GetModelPostData(req)
	id := chi.URLParam(req, "id")
	subscriptionObj, err := subscription.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*subscription.SubscriptionJoined](err)
	}

	if tools.Empty(subscriptionObj) {
		return response.AdminBadRequestError[*subscription.SubscriptionJoined](errors.Errorf("Object not found with ID: %s", id))
	}

	subscriptionObj.MergeData(data)
	err = subscriptionObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*subscription.SubscriptionJoined](err)
	}

	return response.Success(subscriptionObj)
}

func adminCount(_ http.ResponseWriter, req *http.Request) (int64, int, error) {
	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)
	subscription.AddJoinData(parameters)
	count, err := subscription.FindResultsCount(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[int64](err)
	}

	return response.Success(count)
}
