// Code generated by core_gen; DO NOT EDIT.

package subscriptions

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/griffnb/core/lib/log"
	"github.com/griffnb/core/lib/router/request"
	"github.com/griffnb/core/lib/router/response"
	"github.com/griffnb/core/lib/tools"
	"github.com/griffnb/core/lib/types"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/models/subscription"
)

func authIndex(_ http.ResponseWriter, req *http.Request) ([]*subscription.SubscriptionJoined, int, error) {

	user := request.GetReqSession(req).User

	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	subscriptionObjs, err := subscription.FindAllRestrictedJoined(req.Context(), parameters, user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[[]*subscription.SubscriptionJoined]()

	}

	return response.Success(subscriptionObjs)
}

func authGet(_ http.ResponseWriter, req *http.Request) (*subscription.SubscriptionJoined, int, error) {

	user := request.GetReqSession(req).User

	id := chi.URLParam(req, "id")
	subscriptionObj, err := subscription.GetRestrictedJoined(req.Context(), types.UUID(id), user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*subscription.SubscriptionJoined]()

	}

	return response.Success(subscriptionObj)
}
