// Code generated by core_gen; DO NOT EDIT.

package lifecycle_test_placeholders

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/griffnb/core/lib/log"
	"github.com/griffnb/core/lib/router/request"
	"github.com/griffnb/core/lib/router/response"
	"github.com/griffnb/core/lib/tools"
	"github.com/griffnb/core/lib/types"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/models/lifecycle_test_placeholder"
	"github.com/pkg/errors"
)

func adminIndex(_ http.ResponseWriter, req *http.Request) ([]*lifecycle_test_placeholder.LifecycleTestPlaceholderJoined, int, error) {

	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	lifecycleTestPlaceholderObjs, err := lifecycle_test_placeholder.FindAllJoined(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[[]*lifecycle_test_placeholder.LifecycleTestPlaceholderJoined](err)

	}

	return response.Success(lifecycleTestPlaceholderObjs)

}

func adminGet(_ http.ResponseWriter, req *http.Request) (*lifecycle_test_placeholder.LifecycleTestPlaceholderJoined, int, error) {
	id := chi.URLParam(req, "id")

	lifecycleTestPlaceholderObj, err := lifecycle_test_placeholder.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*lifecycle_test_placeholder.LifecycleTestPlaceholderJoined](err)
	}

	return response.Success(lifecycleTestPlaceholderObj)
}

func adminCreate(_ http.ResponseWriter, req *http.Request) (*lifecycle_test_placeholder.LifecycleTestPlaceholder, int, error) {
	userSession := request.GetReqSession(req)
	data := request.GetModelPostData(req)
	lifecycleTestPlaceholderObj := lifecycle_test_placeholder.New()
	lifecycleTestPlaceholderObj.MergeData(data)
	err := lifecycleTestPlaceholderObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*lifecycle_test_placeholder.LifecycleTestPlaceholder](err)

	}

	return response.Success(lifecycleTestPlaceholderObj)
}

func adminUpdate(_ http.ResponseWriter, req *http.Request) (*lifecycle_test_placeholder.LifecycleTestPlaceholderJoined, int, error) {
	userSession := request.GetReqSession(req)
	data := request.GetModelPostData(req)
	id := chi.URLParam(req, "id")
	lifecycleTestPlaceholderObj, err := lifecycle_test_placeholder.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*lifecycle_test_placeholder.LifecycleTestPlaceholderJoined](err)
	}

	if tools.Empty(lifecycleTestPlaceholderObj) {
		return response.AdminBadRequestError[*lifecycle_test_placeholder.LifecycleTestPlaceholderJoined](errors.Errorf("Object not found with ID: %s", id))
	}

	lifecycleTestPlaceholderObj.MergeData(data)
	err = lifecycleTestPlaceholderObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*lifecycle_test_placeholder.LifecycleTestPlaceholderJoined](err)
	}

	return response.Success(lifecycleTestPlaceholderObj)
}

func adminCount(_ http.ResponseWriter, req *http.Request) (int64, int, error) {
	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)
	lifecycle_test_placeholder.AddJoinData(parameters)
	count, err := lifecycle_test_placeholder.FindResultsCount(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[int64](err)
	}

	return response.Success(count)
}
