package sandbox_service

import (
	"context"

	"github.com/griffnb/core/lib/types"
	"github.com/griffnb/techboss-ai-go/internal/environment"
	"github.com/griffnb/techboss-ai-go/internal/integrations/modal"
	"github.com/griffnb/techboss-ai-go/internal/services/github_service"
	"github.com/pkg/errors"
)

// CreateGitHubSandbox creates a Modal sandbox configured for GitHub operations.
// It retrieves an installation token, builds the sandbox config from the GitHub template,
// and injects all necessary environment variables for Git and GitHub CLI operations.
func (s *SandboxService) CreateGitHubSandbox(
	ctx context.Context,
	accountID types.UUID,
	installationID string,
	config *GitHubTemplateConfig,
) (*modal.SandboxInfo, error) {
	// Validate inputs
	if config == nil {
		return nil, errors.New("config cannot be nil")
	}
	if installationID == "" {
		return nil, errors.New("installationID is required")
	}
	if config.Repository == "" {
		return nil, errors.New("repository is required")
	}

	// Get GitHub configuration
	envConfig := environment.GetConfig()
	if envConfig.Github == nil {
		return nil, errors.New("github configuration not found")
	}

	// Create auth service to get installation token
	authService, err := github_service.NewAuthService(
		envConfig.Github.AppID,
		envConfig.Github.PrivateKey,
	)
	if err != nil {
		return nil, errors.Wrapf(err, "failed to create github auth service")
	}

	// Get installation token
	installationToken, err := authService.GetInstallationToken(ctx, installationID)
	if err != nil {
		return nil, errors.Wrapf(err, "failed to get installation token for installation %s", installationID)
	}

	// Build sandbox config from GitHub template
	template := GetGitHubTemplate(config)
	sandboxConfig := template.BuildSandboxConfig(accountID)

	// Set default values for optional fields
	sourceBranch := config.SourceBranch
	if sourceBranch == "" {
		sourceBranch = "main"
	}

	targetBranch := config.TargetBranch
	if targetBranch == "" {
		targetBranch = "ai-changes"
	}

	prTargetBranch := config.PRTargetBranch
	if prTargetBranch == "" {
		prTargetBranch = "main"
	}

	prTitle := config.PRTitle
	if prTitle == "" {
		prTitle = "AI Generated Changes"
	}

	prBody := config.PRBody
	if prBody == "" {
		prBody = "Changes generated by TechBoss AI"
	}

	gitUserName := config.GitUserName
	if gitUserName == "" {
		gitUserName = "TechBoss AI"
	}

	gitUserEmail := config.GitUserEmail
	if gitUserEmail == "" {
		gitUserEmail = "ai@techboss.app"
	}

	// Add environment variables for GitHub operations
	sandboxConfig.EnvironmentVars = map[string]string{
		"GITHUB_TOKEN":     installationToken,
		"REPOSITORY":       config.Repository,
		"SOURCE_BRANCH":    sourceBranch,
		"TARGET_BRANCH":    targetBranch,
		"PR_TARGET_BRANCH": prTargetBranch,
		"PR_TITLE":         prTitle,
		"PR_BODY":          prBody,
		"GIT_USER_NAME":    gitUserName,
		"GIT_USER_EMAIL":   gitUserEmail,
	}

	// Create sandbox using the existing CreateSandbox method
	sandboxInfo, err := s.CreateSandbox(ctx, accountID, sandboxConfig)
	if err != nil {
		return nil, errors.Wrapf(err, "failed to create GitHub sandbox for account %s", accountID)
	}

	return sandboxInfo, nil
}
