// Code generated by core_gen; DO NOT EDIT.

package github_installations

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/griffnb/core/lib/log"
	"github.com/griffnb/core/lib/router/request"
	"github.com/griffnb/core/lib/router/response"
	"github.com/griffnb/core/lib/tools"
	"github.com/griffnb/core/lib/types"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/models/github_installation"
	"github.com/pkg/errors"
)

//	 Gets a list of GithubInstallation entries
//
//		@Title			List GithubInstallation
//
//		@Summary		List GithubInstallation
//		@Description	List GithubInstallation
//		@Tags			GitHub
//		@Tags			AdminOnly
//		@Tags			CRUD
//		@Accept			json
//		@Produce		json
//		@Param			q	query		string	false	"search by q"
//		@Param			limit	query		int		false	"limit results"		default(100)	minimum(1)	maximum(1000)
//		@Param			offset	query		int		false	"offset results"	default(0)	minimum(0)
//		@Param			order	query		string	false	"sort results e.g. 'created_at desc'"	default(created_at desc)
//		@Param			filters	query		string	false	"filters, see readme"
//		@Success		200	{object}	response.SuccessResponse{data=[]github_installation.GithubInstallationJoined}
//		@Failure		400	{object}	response.ErrorResponse
//		@Failure		404	{object}	response.ErrorResponse
//		@Failure		500	{object}	response.ErrorResponse
//		@Router			/admin/github_installation [get]
func adminIndex(_ http.ResponseWriter, req *http.Request) ([]*github_installation.GithubInstallationJoined, int, error) {

	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	githubInstallationObjs, err := github_installation.FindAllJoined(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[[]*github_installation.GithubInstallationJoined](err)

	}

	return response.Success(githubInstallationObjs)

}

//	 Gets a GithubInstallation entry by ID
//
//		@Title			Get GithubInstallation
//
//		@Summary		Get GithubInstallation
//		@Description	Get GithubInstallation
//		@Tags			GitHub
//		@Tags			AdminOnly
//		@Tags			CRUD
//		@Accept			json
//		@Produce		json
//		@Param			id	path		string	true	"GithubInstallation ID"
//		@Success		200	{object}	response.SuccessResponse{data=github_installation.GithubInstallationJoined}
//		@Failure		400	{object}	response.ErrorResponse
//		@Failure		404	{object}	response.ErrorResponse
//		@Failure		500	{object}	response.ErrorResponse
//		@Router			/admin/github_installation/{id} [get]
func adminGet(_ http.ResponseWriter, req *http.Request) (*github_installation.GithubInstallationJoined, int, error) {
	id := chi.URLParam(req, "id")

	githubInstallationObj, err := github_installation.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*github_installation.GithubInstallationJoined](err)
	}

	return response.Success(githubInstallationObj)
}

//	 Creates a GithubInstallation entry
//
//		@Title			Create GithubInstallation
//
//		@Summary		Create GithubInstallation
//		@Description	Create GithubInstallation
//		@Tags			GitHub
//		@Tags			AdminOnly
//		@Tags			CRUD
//		@Accept			json
//		@Produce		json
//		@Param			data	body		github_installation.GithubInstallation	true	"GithubInstallation Data"
//		@Success		200	{object}	response.SuccessResponse{data=github_installation.GithubInstallation}
//		@Failure		400	{object}	response.ErrorResponse
//		@Failure		404	{object}	response.ErrorResponse
//		@Failure		500	{object}	response.ErrorResponse
//		@Router			/admin/github_installation/ [post]
func adminCreate(_ http.ResponseWriter, req *http.Request) (*github_installation.GithubInstallation, int, error) {
	userSession := request.GetReqSession(req)
	data := request.GetModelPostData(req)
	githubInstallationObj := github_installation.New()
	githubInstallationObj.MergeData(data)
	err := githubInstallationObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*github_installation.GithubInstallation](err)

	}

	return response.Success(githubInstallationObj)
}

//	 Updates a GithubInstallation entry
//
//		@Title			Update GithubInstallation
//
//		@Summary		Update GithubInstallation
//		@Description	Update GithubInstallation
//		@Tags			GitHub
//		@Tags			AdminOnly
//		@Tags			CRUD
//		@Accept			json
//		@Produce		json
//	 @Param 			id	path		string	true	"GithubInstallation ID"
//		@Param			data	body		github_installation.GithubInstallation	true	"GithubInstallation Data"
//		@Success		200	{object}	response.SuccessResponse{data=github_installation.GithubInstallation}
//		@Failure		400	{object}	response.ErrorResponse
//		@Failure		404	{object}	response.ErrorResponse
//		@Failure		500	{object}	response.ErrorResponse
//		@Router			/admin/github_installation/{id} [put]
func adminUpdate(_ http.ResponseWriter, req *http.Request) (*github_installation.GithubInstallationJoined, int, error) {
	userSession := request.GetReqSession(req)
	data := request.GetModelPostData(req)
	id := chi.URLParam(req, "id")
	githubInstallationObj, err := github_installation.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*github_installation.GithubInstallationJoined](err)
	}

	if tools.Empty(githubInstallationObj) {
		return response.AdminBadRequestError[*github_installation.GithubInstallationJoined](errors.Errorf("Object not found with ID: %s", id))
	}

	githubInstallationObj.MergeData(data)
	err = githubInstallationObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*github_installation.GithubInstallationJoined](err)
	}

	return response.Success(githubInstallationObj)
}

//	 Gets the count of GithubInstallation entries
//
//		@Title			Count GithubInstallation
//
//		@Summary		Count GithubInstallation
//		@Description	Count GithubInstallation
//		@Tags			GitHub
//		@Tags			AdminOnly
//		@Tags			CRUD
//		@Accept			json
//		@Produce		json
//		@Param			q	query		string	false	"search by q"
//		@Param			filters	query		string	false	"filters, see readme"
//		@Success		200	{object}	response.SuccessResponse{data=int64}
//		@Failure		400	{object}	response.ErrorResponse
//		@Failure		404	{object}	response.ErrorResponse
//		@Failure		500	{object}	response.ErrorResponse
//		@Router			/admin/github_installation/count [get]
func adminCount(_ http.ResponseWriter, req *http.Request) (int64, int, error) {
	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)
	github_installation.AddJoinData(parameters)
	count, err := github_installation.FindResultsCount(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[int64](err)
	}

	return response.Success(count)
}
