// Code generated by core_generate; DO NOT EDIT.

package accounts

import (
	"net/http"

	"github.com/CrowdShield/go-core/lib/log"
	"github.com/CrowdShield/go-core/lib/router"
	"github.com/CrowdShield/go-core/lib/tools"
	"github.com/CrowdShield/go-core/lib/types"
	"github.com/go-chi/chi/v5"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/controllers/helpers"
	"github.com/griffnb/techboss-ai-go/internal/models/account"
)

func authIndex(_ http.ResponseWriter, req *http.Request) ([]*account.AccountJoined, int, error) {
	userSession := helpers.GetReqSession(req)

	user := userSession.User

	parameters := router.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	accountObjs, err := account.FindAllRestrictedJoined(req.Context(), parameters, user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.PublicBadRequestError[[]*account.AccountJoined]()

	}

	return helpers.Success(accountObjs)
}

func authGet(_ http.ResponseWriter, req *http.Request) (*account.AccountJoined, int, error) {
	userSession := helpers.GetReqSession(req)

	user := userSession.User

	id := chi.URLParam(req, "id")
	accountObj, err := account.GetRestrictedJoined(req.Context(), types.UUID(id), user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.PublicBadRequestError[*account.AccountJoined]()

	}

	return helpers.Success(accountObj)
}

func authCreate(_ http.ResponseWriter, req *http.Request) (*account.Account, int, error) {
	if helpers.IsSuperUpdate(req) {
		return helpers.PublicCustomError[*account.Account]("not allowed to update as super user", http.StatusBadRequest)
	}

	userSession := helpers.GetReqSession(req)

	user := userSession.User

	rawdata := router.GetJSONPostData(req)
	data := helpers.ConvertPost(rawdata)
	accountObj := account.NewPublic(data, user)
	err := accountObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.PublicBadRequestError[*account.Account]()

	}

	return helpers.Success(accountObj)
}

func authUpdate(_ http.ResponseWriter, req *http.Request) (*account.AccountJoined, int, error) {
	if helpers.IsSuperUpdate(req) {
		return helpers.PublicCustomError[*account.AccountJoined]("not allowed to update as super user", http.StatusBadRequest)
	}

	userSession := helpers.GetReqSession(req)

	user := userSession.User

	id := chi.URLParam(req, "id")
	rawdata := router.GetJSONPostData(req)
	data := helpers.ConvertPost(rawdata)
	accountObj, err := account.GetRestrictedJoined(req.Context(), types.UUID(id), user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.PublicBadRequestError[*account.AccountJoined]()
	}

	account.UpdatePublic(&accountObj.Account, data, user)
	err = accountObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return helpers.PublicBadRequestError[*account.AccountJoined]()
	}

	return helpers.Success(accountObj)
}
