// Code generated by core_generate; DO NOT EDIT.

package accounts

import (
	"net/http"

	"github.com/CrowdShield/go-core/lib/log"
	"github.com/CrowdShield/go-core/lib/router/request"
	"github.com/CrowdShield/go-core/lib/router/response"
	"github.com/CrowdShield/go-core/lib/tools"
	"github.com/CrowdShield/go-core/lib/types"
	"github.com/go-chi/chi/v5"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/models/account"
)

func authIndex(_ http.ResponseWriter, req *http.Request) ([]*account.AccountJoined, int, error) {

	user := request.GetReqSession(req).User

	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	accountObjs, err := account.FindAllRestrictedJoined(req.Context(), parameters, user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[[]*account.AccountJoined]()

	}

	return response.Success(accountObjs)
}

func authGet(_ http.ResponseWriter, req *http.Request) (*account.AccountJoined, int, error) {

	user := request.GetReqSession(req).User

	id := chi.URLParam(req, "id")
	accountObj, err := account.GetRestrictedJoined(req.Context(), types.UUID(id), user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*account.AccountJoined]()

	}

	return response.Success(accountObj)
}

func authCreate(_ http.ResponseWriter, req *http.Request) (*account.Account, int, error) {

	user := request.GetReqSession(req).User

	data := request.GetModelPostData(req)
	accountObj := account.NewPublic(data, user)
	err := accountObj.Save(user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*account.Account]()

	}

	return response.Success(accountObj)
}

func authUpdate(_ http.ResponseWriter, req *http.Request) (*account.AccountJoined, int, error) {

	user := request.GetReqSession(req).User

	id := chi.URLParam(req, "id")
	data := request.GetModelPostData(req)
	accountObj, err := account.GetRestrictedJoined(req.Context(), types.UUID(id), user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*account.AccountJoined]()
	}

	account.UpdatePublic(&accountObj.Account, data, user)
	err = accountObj.Save(user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*account.AccountJoined]()
	}

	return response.Success(accountObj)
}
