// Code generated by core_generate; DO NOT EDIT.

package agents

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/griffnb/core/lib/log"
	"github.com/griffnb/core/lib/router/request"
	"github.com/griffnb/core/lib/router/response"
	"github.com/griffnb/core/lib/tools"
	"github.com/griffnb/core/lib/types"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/models/agent"
	"github.com/pkg/errors"
)

func adminIndex(_ http.ResponseWriter, req *http.Request) ([]*agent.AgentJoined, int, error) {

	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	agentObjs, err := agent.FindAllJoined(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[[]*agent.AgentJoined](err)

	}

	return response.Success(agentObjs)

}

func adminGet(_ http.ResponseWriter, req *http.Request) (*agent.AgentJoined, int, error) {
	id := chi.URLParam(req, "id")

	agentObj, err := agent.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*agent.AgentJoined](err)
	}

	return response.Success(agentObj)
}

func adminCreate(_ http.ResponseWriter, req *http.Request) (*agent.Agent, int, error) {
	userSession := request.GetReqSession(req)
	data := request.GetModelPostData(req)
	agentObj := agent.New()
	agentObj.MergeData(data)
	err := agentObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*agent.Agent](err)

	}

	return response.Success(agentObj)
}

func adminUpdate(_ http.ResponseWriter, req *http.Request) (*agent.AgentJoined, int, error) {
	userSession := request.GetReqSession(req)
	data := request.GetModelPostData(req)
	id := chi.URLParam(req, "id")
	agentObj, err := agent.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*agent.AgentJoined](err)
	}

	if tools.Empty(agentObj) {
		return response.AdminBadRequestError[*agent.AgentJoined](errors.Errorf("Object not found with ID: %s", id))
	}

	agentObj.MergeData(data)
	err = agentObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*agent.AgentJoined](err)
	}

	return response.Success(agentObj)
}

func adminCount(_ http.ResponseWriter, req *http.Request) (int64, int, error) {
	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)
	agent.AddJoinData(parameters)
	count, err := agent.FindResultsCount(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[int64](err)
	}

	return response.Success(count)
}
