// Code generated by core_generate; DO NOT EDIT.

package global_configs

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/griffnb/core/lib/log"
	"github.com/griffnb/core/lib/router/request"
	"github.com/griffnb/core/lib/router/response"
	"github.com/griffnb/core/lib/tools"
	"github.com/griffnb/core/lib/types"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/models/global_config"
	"github.com/pkg/errors"
)

func adminIndex(_ http.ResponseWriter, req *http.Request) ([]*global_config.GlobalConfigJoined, int, error) {

	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	globalConfigObjs, err := global_config.FindAllJoined(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[[]*global_config.GlobalConfigJoined](err)

	}

	return response.Success(globalConfigObjs)

}

func adminGet(_ http.ResponseWriter, req *http.Request) (*global_config.GlobalConfigJoined, int, error) {
	id := chi.URLParam(req, "id")

	globalConfigObj, err := global_config.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*global_config.GlobalConfigJoined](err)
	}

	return response.Success(globalConfigObj)
}

func adminCreate(_ http.ResponseWriter, req *http.Request) (*global_config.GlobalConfig, int, error) {
	userSession := request.GetReqSession(req)
	data := request.GetModelPostData(req)
	globalConfigObj := global_config.New()
	globalConfigObj.MergeData(data)
	err := globalConfigObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*global_config.GlobalConfig](err)

	}

	return response.Success(globalConfigObj)
}

func adminUpdate(_ http.ResponseWriter, req *http.Request) (*global_config.GlobalConfigJoined, int, error) {
	userSession := request.GetReqSession(req)
	data := request.GetModelPostData(req)
	id := chi.URLParam(req, "id")
	globalConfigObj, err := global_config.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*global_config.GlobalConfigJoined](err)
	}

	if tools.Empty(globalConfigObj) {
		return response.AdminBadRequestError[*global_config.GlobalConfigJoined](errors.Errorf("Object not found with ID: %s", id))
	}

	globalConfigObj.MergeData(data)
	err = globalConfigObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*global_config.GlobalConfigJoined](err)
	}

	return response.Success(globalConfigObj)
}

func adminCount(_ http.ResponseWriter, req *http.Request) (int64, int, error) {
	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)
	global_config.AddJoinData(parameters)
	count, err := global_config.FindResultsCount(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[int64](err)
	}

	return response.Success(count)
}
