// Code generated by core_generate; DO NOT EDIT.

package billing_plans

import (
	"net/http"

	"github.com/CrowdShield/go-core/lib/log"
	"github.com/CrowdShield/go-core/lib/router/request"
	"github.com/CrowdShield/go-core/lib/router/response"
	"github.com/CrowdShield/go-core/lib/types"
	"github.com/go-chi/chi/v5"
	"github.com/griffnb/techboss-ai-go/internal/models/billing_plan"
)

func authGet(_ http.ResponseWriter, req *http.Request) (*billing_plan.BillingPlanJoined, int, error) {

	user := request.GetReqSession(req).User

	id := chi.URLParam(req, "id")
	billingPlanObj, err := billing_plan.GetRestrictedJoined(req.Context(), types.UUID(id), user)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.PublicBadRequestError[*billing_plan.BillingPlanJoined]()

	}

	return response.Success(billingPlanObj)
}
