// Code generated by core_generate; DO NOT EDIT.

package billing_plans

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/griffnb/core/lib/log"
	"github.com/griffnb/core/lib/router/request"
	"github.com/griffnb/core/lib/router/response"
	"github.com/griffnb/core/lib/tools"
	"github.com/griffnb/core/lib/types"
	"github.com/griffnb/techboss-ai-go/internal/constants"
	"github.com/griffnb/techboss-ai-go/internal/models/billing_plan"
	"github.com/pkg/errors"
)

func adminIndex(_ http.ResponseWriter, req *http.Request) ([]*billing_plan.BillingPlanJoined, int, error) {

	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)

	if tools.Empty(parameters.Limit) {
		parameters.Limit = constants.SYSTEM_LIMIT
	}

	if !tools.Empty(req.URL.Query().Get("q")) {
		addSearch(parameters, req.URL.Query().Get("q"))
	}

	billingPlanObjs, err := billing_plan.FindAllJoined(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[[]*billing_plan.BillingPlanJoined](err)

	}

	return response.Success(billingPlanObjs)

}

func adminGet(_ http.ResponseWriter, req *http.Request) (*billing_plan.BillingPlanJoined, int, error) {
	id := chi.URLParam(req, "id")

	billingPlanObj, err := billing_plan.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*billing_plan.BillingPlanJoined](err)
	}

	return response.Success(billingPlanObj)
}

func adminCreate(_ http.ResponseWriter, req *http.Request) (*billing_plan.BillingPlan, int, error) {
	userSession := request.GetReqSession(req)
	data := request.GetModelPostData(req)
	billingPlanObj := billing_plan.New()
	billingPlanObj.MergeData(data)
	err := billingPlanObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*billing_plan.BillingPlan](err)

	}

	return response.Success(billingPlanObj)
}

func adminUpdate(_ http.ResponseWriter, req *http.Request) (*billing_plan.BillingPlanJoined, int, error) {
	userSession := request.GetReqSession(req)
	data := request.GetModelPostData(req)
	id := chi.URLParam(req, "id")
	billingPlanObj, err := billing_plan.GetJoined(req.Context(), types.UUID(id))
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*billing_plan.BillingPlanJoined](err)
	}

	if tools.Empty(billingPlanObj) {
		return response.AdminBadRequestError[*billing_plan.BillingPlanJoined](errors.Errorf("Object not found with ID: %s", id))
	}

	billingPlanObj.MergeData(data)
	err = billingPlanObj.Save(userSession.User)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[*billing_plan.BillingPlanJoined](err)
	}

	return response.Success(billingPlanObj)
}

func adminCount(_ http.ResponseWriter, req *http.Request) (int64, int, error) {
	parameters := request.BuildIndexParams(req.Context(), req.URL.Query(), TABLE_NAME)
	billing_plan.AddJoinData(parameters)
	count, err := billing_plan.FindResultsCount(req.Context(), parameters)
	if err != nil {
		log.ErrorContext(err, req.Context())
		return response.AdminBadRequestError[int64](err)
	}

	return response.Success(count)
}
